name: Test workflow
on:
  push:
    branches:
      - master
jobs:
  test_1:
    runs-on: ubuntu-20.04
    steps:
      - name: Download files
        uses: actions/checkout@v3

      - name: Install pycodestyle linter
        run: python -m pip install pycodestyle==2.8.0

      - id: updated_files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'

      - name: save
        run: echo ${{ steps.updated_files.outputs.added_modified }} > updated_files.txt

      - name: print
        run: cat updated_files.txt

      - name: print
        run: ls -la

      # - name: Run pycodestyle linter
      #   run: |
      #     mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.updated_files.outputs.added_modified }}')
      #     for added_modified_file in "${added_modified_files[@]}"; do
      #       pycodestyle --max-line-length=120 ${added_modified_file}
      #     done
