name: Test workflow
on:
  push:
    branches:
      - master
jobs:
  test_1:
    runs-on: ubuntu-20.04
    steps:
      - name: Check python2
        run: python --version

      - name: Check python3
        run: python3 --version

