name: Test workflow
on:
  push:
    branches:
      - master
jobs:
  test_1:
    runs-on: ubuntu-20.04
    steps:
      - name: Check python2
        run: python --version

      - name: Check python3
        run: python3 --version

      - id: files
        name: Print modifies files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "Do something with this ${added_modified_file}."
          done

      - name: print
        run: cat .github/workflows/test.yaml
