name: Test workflow
on:
  push

jobs:
  test_1:
    runs-on: ubuntu-20.04
    steps:
      - name: Download files
        uses: actions/checkout@v3

      - name: Install pycodestyle linter
        run: python -m pip install pycodestyle==2.8.0

      - name: Get the updated files
        id: updated_files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'

      - name: Save the updated files data
        run: echo ${{ steps.updated_files.outputs.added_modified }} > updated_files.txt

      - name: Run linter script
        run: |
          chmod +x .github/workflows/scripts/linter.py
          python .github/workflows/scripts/linter.py --file updated_files.txt
