name: Test workflow
on:
  push

jobs:
  test_1:
    runs-on: ubuntu-20.04
    steps:
      - name: Download files
        uses: actions/checkout@v3

      - name: Install pycodestyle linter
        run: python -m pip install pycodestyle==2.8.0

      - id: updated_files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'

      - name: save
        run: echo ${{ steps.updated_files.outputs.added_modified }} > updated_files.txt

      - name: test
        run: sudo apt install -y tree && tree .github

      - name: ls
        run: ls -la .github/workflows/scripts/

      - name: cat
        run: cat .github/workflows/scripts/linter.py

      - name: Run linter script
        run: |
          # make file runnable, might not be necessary
          chmod +x .github/workflows/scripts/linter.py

          # run script
          python .github/workflows/scripts/linter.py --file updated_files.txt
